from typing import Any

from langchain_core.callbacks.manager import CallbackManagerForRetrieverRun
from langchain_core.documents import Document
from langchain_core.prompts import PromptTemplate
from langchain_core.retrievers import BaseRetriever
from langchain_core.vectorstores import VectorStore
from pydantic import ConfigDict

from config import TOP_K

# HyDE (Hypothetical Document Embeddings): asking the LLM to write a
# hypothetical passage that answers the question, then embedding that
# passage, puts the search vector in the same region of embedding space as
# the real answer passage — closer than the raw question's embedding, which
# is phrased as a question rather than as prose.
HYDE_PROMPT = PromptTemplate(
    input_variables=["question"],
    template=(
        "Write a short hypothetical passage that directly answers the "
        "question below, as if it were an excerpt from the source document "
        "being searched. Do not mention that this is hypothetical or refer "
        "to the question itself.\n\n"
        "Question: {question}\n"
        "Passage:"
    ),
)


class HydeRetriever(BaseRetriever):
    """Retriever that runs similarity search against the embedding of a
    hypothetical answer (generated by `llm`) rather than the raw query."""

    vectorstore: VectorStore
    # Typed loosely (any object with an `.invoke(prompt) -> message with
    # .content` method, e.g. a ChatOpenAI instance) rather than
    # BaseLanguageModel: BaseLanguageModel is itself a pydantic model, so
    # pydantic would reject any duck-typed stand-in passed at construction.
    llm: Any
    k: int = TOP_K

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun, **kwargs: Any
    ) -> list[Document]:
        hypothetical_answer = self.llm.invoke(HYDE_PROMPT.format(question=query)).content
        embedding = self.vectorstore.embeddings.embed_query(hypothetical_answer)
        return self.vectorstore.similarity_search_by_vector(embedding, k=self.k)
